// UBIGEO del Perú: Departamento → Provincia → Distrito.
// Datos basados en la división administrativa oficial (INEI).
// Se usa en EmpresaForm para registrar la ubicación de las empresas.

export type Ubigeo = Record<string, Record<string, string[]>>;

export const PERU_UBIGEO: Ubigeo = {
  Amazonas: {
    Chachapoyas: [
      "Chachapoyas",
      "Asunción",
      "Balsas",
      "Cheto",
      "Chiliquín",
      "Chuquibamba",
      "Granada",
      "Huancas",
      "La Jalca",
      "Leimebamba",
      "Levanto",
      "Magdalena",
      "Mariscal Castilla",
      "Molinopampa",
      "Montevideo",
      "Olleros",
      "Quinjalca",
      "San Francisco de Daguas",
      "San Isidro de Maino",
      "Soloco",
      "Sonche",
    ],
    Bagua: [
      "Bagua",
      "Aramango",
      "Copallín",
      "El Parco",
      "Imaza",
      "La Peca",
    ],
    Bongará: [
      "Jumbilla",
      "Chisquilla",
      "Churuja",
      "Corosha",
      "Cuispes",
      "Florida",
      "Jazán",
      "Recta",
      "San Carlos",
      "Shipasbamba",
      "Valera",
      "Yambrasbamba",
    ],
    Condorcanqui: ["El Cenepa", "Nieva", "Río Santiago"],
    Luya: [
      "Lamud",
      "Camporredondo",
      "Cocabamba",
      "Colcamar",
      "Conila",
      "Inguilpata",
      "Longuita",
      "Lonya Chico",
      "Luya",
      "Luya Viejo",
      "María",
      "Ocalli",
      "Ocumal",
      "Pisuquía",
      "Providencia",
      "San Cristóbal",
      "San Francisco de Yeso",
      "San Jerónimo",
      "San Juan de Lopecancha",
      "Santa Catalina",
      "Santo Tomás",
      "Tingo",
      "Trita",
    ],
    RodríguezdeMendoza: [
      "San Nicolás",
      "Chirimoto",
      "Cochamal",
      "Huambo",
      "Limabamba",
      "Longar",
      "Mariscal Benavides",
      "Milpuc",
      "Omia",
      "Santa Rosa",
      "Totora",
      "Vista Alegre",
    ],
    Utcubamba: [
      "Bagua Grande",
      "Cajaruro",
      "Cumba",
      "El Milagro",
      "Huarango",
      "Jamalca",
      "Lonya Grande",
      "Yamaluc",
    ],
  },
  Áncash: {
    Huaraz: [
      "Huaraz",
      "Cochabamba",
      "Colcabamba",
      "Huanchay",
      "Independencia",
      "Jangas",
      "La Libertad",
      "Olleros",
      "Pampas",
      "Pariacoto",
      "Pira",
      "Tarica",
    ],
    Aija: ["Aija", "Coris", "Huacllán", "La Merced", "Succha"],
    "Antonio Raymondi": ["Chacas", "Acochaca"],
    Asunción: ["Chacas", "Acochaca"],
    Bolognesi: [
      "Chiquián",
      "Abelardo Pardo Lezameta",
      "Antonio Raymondi",
      "Aquia",
      "Cajacay",
      "Canis",
      "Colquioc",
      "Huallanca",
      "Huasta",
      "Huayllacayán",
      "La Primavera",
      "Mangas",
      "Pacllón",
      "San Miguel de Corpanqui",
      "Ticllos",
      "Taquía",
    ],
    Carhuaz: [
      "Carhuaz",
      "Acopampa",
      "Amashca",
      "Anta",
      "Ataquero",
      "Marcará",
      "Pariahuanca",
      "San Miguel de Aco",
      "Shilla",
      "Tinco",
      "Yungar",
    ],
    "Carlos Fermín Fitzcarrald": ["San Luis", "San Nicolás", "Yauya"],
    Casma: ["Casma", "Buena Vista Alta", "Comandante Noel", "Yaután"],
    Corongo: ["Corongo", "Aco", "Bambas", "Cusca", "La Pampa", "Yánac", "Yupán"],
    Huaylas: [
      "Caraz",
      "Huallanca",
      "Huata",
      "Huaylas",
      "Mato",
      "Pamparomás",
      "Pueblo Libre",
      "Santa Cruz",
      "Santo Toribio",
      "Yuracmarca",
    ],
    Huarmey: ["Huarmey", "Cochapeti", "Culebras", "Huayan", "Malvas"],
    MariscalLuzuriaga: [
      "Piscobamba",
      "Acobamba",
      "Casca",
      "Eleazar Guzmán Barrón",
      "Fidel Olivas Escudero",
      "Llama",
      "Llumpa",
      "Lucma",
      "Musga",
      "Yupán",
    ],
    Ocros: [
      "Ocros",
      "Acas",
      "Cajamarquilla",
      "Carhuapampa",
      "Cochas",
      "Congas",
      "Llipa",
      "San Cristóbal de Raján",
      "San Pedro",
      "Santiago de Chilcas",
    ],
    Pallasca: [
      "Cabana",
      "Bolognesi",
      "Conchucos",
      "Huacaschuque",
      "Huandoval",
      "Lacabamba",
      "Llapo",
      "Pallasca",
      "Pampas",
      "Santa Rosa",
      "Tauca",
    ],
    Pomabamba: [
      "Pomabamba",
      "Huayllán",
      "Parobamba",
      "Quinuabamba",
      "San Ignacio",
    ],
    Recuay: [
      "Recuay",
      "Catac",
      "Cotaparaco",
      "Huayllapampa",
      "Llacllín",
      "Marca",
      "Pampas Chico",
      "Pararín",
      "Tapacocha",
      "Ticapampa",
    ],
    Santa: [
      "Chimbote",
      "Cáceres del Perú",
      "Coishco",
      "Macate",
      "Moro",
      "Nepeña",
      "Samanco",
      "Santa",
      "Nuevo Chimbote",
    ],
    Sihuas: [
      "Sihuas",
      "Acobamba",
      "Alfonso Ugarte",
      "Cashapampa",
      "Chingalpo",
      "Huayllabamba",
      "Quiches",
      "Ragash",
      "San Juan",
      "Sicsibamba",
    ],
    Yungay: [
      "Yungay",
      "Cascapara",
      "Mancos",
      "Matacoto",
      "Quillo",
      "Ranrahirca",
      "Shupluy",
      "Yanama",
    ],
  },
  Apurímac: {
    Abancay: [
      "Abancay",
      "Chacoche",
      "Circa",
      "Curahuasi",
      "Huanipaca",
      "Lambrama",
      "Pichirhua",
      "San Pedro de Cachora",
      "Tambobamba",
      "Tirapata",
    ],
    Andahuaylas: [
      "Andahuaylas",
      "Andarapa",
      "Chiara",
      "Huancarama",
      "Huancaray",
      "Huayana",
      "Kishuara",
      "Pacobamba",
      "Pacucha",
      "Pampachiri",
      "Pomacocha",
      "San Antonio de Cachi",
      "San Jerónimo",
      "San Miguel de Chaccrampa",
      "Santa María de Chicmo",
      "Talavera",
      "Tumay Huaraca",
      "Turpo",
      "Kaquiabamba",
    ],
    Antabamba: [
      "Antabamba",
      "El Oro",
      "Huaquirca",
      "Juan Espinoza Medrano",
      "Oropesa",
      "Pachaconas",
      "Sabaino",
    ],
    Aymaraes: [
      "Chalhuanca",
      "Capaya",
      "Caraybamba",
      "Chapimarca",
      "Colcabamba",
      "Cotaruse",
      "Huayllo",
      "Justo Apu Sahuaraura",
      "Lucre",
      "Pocohuanca",
      "San Juan de Chacña",
      "Sañayca",
      "Soraya",
      "Tapairihua",
      "Tintay",
      "Toraya",
      "Yanaca",
    ],
    Cotabambas: [
      "Tambobamba",
      "Cotabambas",
      "Coyllurqui",
      "Haquira",
      "Mara",
      "Challhuahuacho",
    ],
    Chincheros: [
      "Chincheros",
      "Anco_Huallo",
      "Cocharcas",
      "Huaccana",
      "Ocobamba",
      "Ongoy",
      "Uranmarca",
      "Ranracancha",
    ],
    Grau: [
      "Chuquibambilla",
      "Curpahuasi",
      "Gamarra",
      "Huayllati",
      "Mamara",
      "Micaela Bastidas",
      "Pataypampa",
      "Progreso",
      "San Antonio",
      "Santa Rosa",
      "Turpay",
      "Vilcabamba",
      "Virundo",
    ],
  },
  Arequipa: {
    Arequipa: [
      "Arequipa",
      "Alto Selva Alegre",
      "Cayma",
      "Cerro Colorado",
      "Characato",
      "Chiguata",
      "Jacobo Hunter",
      "La Joya",
      "Mariano Melgar",
      "Miraflores",
      "Mollebaya",
      "Paucarpata",
      "Pocsi",
      "Polobaya",
      "Quequeña",
      "Sabandia",
      "Sachaca",
      "San Juan de Siguas",
      "San Juan de Tarucani",
      "Santa Isabel de Siguas",
      "Santa Rita de Siguas",
      "Socabaya",
      "Tiabaya",
      "Uchumayo",
      "Vitor",
      "Yanahuara",
      "Yarabamba",
      "Yura",
    ],
    Camaná: [
      "Camaná",
      "José María Quimper",
      "Mariano Nicolás Valcárcel",
      "Mariscal Cáceres",
      "Nicolás de Piérola",
      "Ocoña",
      "Quilca",
      "Samuel Pastor",
    ],
    Caravelí: [
      "Caravelí",
      "Acarí",
      "Atico",
      "Atiquipa",
      "Bella Unión",
      "Cahuacho",
      "Chala",
      "Chaparra",
      "Huanuhuanu",
      "Jaqui",
      "Lomas",
      "Quicacha",
      "Yauca",
    ],
    Castilla: [
      "Aplao",
      "Andagua",
      "Ayo",
      "Chachas",
      "Chilcaymarca",
      "Choco",
      "Huancarqui",
      "Machaguay",
      "Orcopampa",
      "Pampacolca",
      "Tipán",
      "Uñón",
      "Uraca",
      "Viraco",
    ],
    Caylloma: [
      "Chivay",
      "Achoma",
      "Cabanaconde",
      "Callalli",
      "Caylloma",
      "Chalhuanca",
      "Choco",
      "Huanca",
      "Ichupampa",
      "Lari",
      "Lluta",
      "Maca",
      "Madrigal",
      "Majes",
      "San Antonio de Chuca",
      "Sibayo",
      "Tapay",
      "Tisco",
      "Tuti",
      "Yanque",
    ],
    Condesuyos: [
      "Chuquibamba",
      "Andaray",
      "Cayarani",
      "Chichas",
      "Iray",
      "Río Grande",
      "Salamanca",
      "Yanaquihua",
    ],
    Islay: [
      "Mollendo",
      "Cocachacra",
      "Dean Valdivia",
      "Islay",
      "Mejía",
      "Punta de Bombón",
    ],
    "La Unión": [
      "Cotahuasi",
      "Alca",
      "Charcana",
      "Huaynacotas",
      "Pampamarca",
      "Puyca",
      "Quechualla",
      "Sayla",
      "Tauría",
      "Tomepampa",
      "Toro",
    ],
  },
  Ayacucho: {
    Huamanga: [
      "Ayacucho",
      "Acocro",
      "Acos Vinchos",
      "Carmen Alto",
      "Chiara",
      "Ocros",
      "Pacaycasa",
      "Quinua",
      "San José de Ticllas",
      "San Juan Bautista",
      "Santiago de Pischa",
      "Socos",
      "Tambillo",
      "Vinchos",
      "Jesús Nazareno",
    ],
    Cangallo: [
      "Cangallo",
      "Chuschi",
      "Los Morochucos",
      "María Parado de Bellido",
      "Paras",
      "Totos",
    ],
    "Huanca Sancos": [
      "Huanca Sancos",
      "Carapo",
      "Sacsamarca",
      "Santiago de Lucanamarca",
    ],
    Huanta: [
      "Huanta",
      "Ayahuanco",
      "Huamanguilla",
      "Iguain",
      "Llochegua",
      "Luricocha",
      "San Miguel de Mayocc",
      "Santillana",
      "Sivia",
      "Tambo",
    ],
    "La Mar": [
      "San Miguel",
      "Anco",
      "Ayna",
      "Chilcas",
      "Chungui",
      "Luis Carranza",
      "Santa Rosa",
      "Tambo",
      "Samugari",
    ],
    Lucanas: [
      "Puquio",
      "Aucara",
      "Cabana",
      "Carmen Salcedo",
      "Chaviña",
      "Chipao",
      "Huacaña",
      "Laramate",
      "Leoncio Prado",
      "Llauta",
      "Lucanas",
      "Ocaña",
      "Otoca",
      "Saisa",
      "San Cristóbal",
      "San Juan",
      "San Pedro",
      "San Pedro de Palco",
      "Sancos",
      "Santa Ana de Huaycahuacho",
      "Santa Lucía",
    ],
    Parinacochas: [
      "Coracora",
      "Chumpi",
      "Coronel Castañeda",
      "Pacapausa",
      "Pullo",
      "Puyusca",
      "San Francisco de Ravacayco",
      "Upahuacho",
    ],
    "Paucar del Sara Sara": [
      "Pausa",
      "Colta",
      "Corculla",
      "Lampa",
      "Marcabamba",
      "Oyolo",
      "Pararca",
      "San Javier de Alpabamba",
      "San José de Ushua",
      "Sara Sara",
    ],
    Sucre: [
      "Querobamba",
      "Belén",
      "Chalcos",
      "Chilcayoc",
      "Huacaña",
      "Morcolla",
      "Paico",
      "San Pedro de Larcay",
      "San Salvador de Quije",
      "Santiago de Paucaray",
      "Soras",
    ],
    VíctorFajardo: [
      "Huancapi",
      "Alcamenca",
      "Apongo",
      "Asquipata",
      "Canaria",
      "Cayara",
      "Colca",
      "Huamanquiquia",
      "Huancarpun",
      "Huaya",
      "Sarhua",
      "Vilcanchos",
    ],
    VilcasHuamán: [
      "Vilcashuamán",
      "Accomarca",
      "Carhuanca",
      "Concepción",
      "Huambalpa",
      "Independencia",
      "Saurama",
      "Vischongo",
    ],
  },
  Cajamarca: {
    Cajamarca: [
      "Cajamarca",
      "Asunción",
      "Chetilla",
      "Cospán",
      "Encañada",
      "Jesús",
      "Llacanora",
      "Los Baños del Inca",
      "Magdalena",
      "Matara",
      "Namora",
      "San Juan",
    ],
    Cajabamba: [
      "Cajabamba",
      "Cachachi",
      "Condebamba",
      "Sitacocha",
    ],
    Celendín: [
      "Celendín",
      "Chumuch",
      "Cortegana",
      "Huasmín",
      "Jorge Chávez",
      "José Gálvez",
      "La Libertad de Pallán",
      "Miguel Iglesias",
      "Oxamarca",
      "Sorochuco",
      "Sucre",
      "Utco",
    ],
    Chota: [
      "Chota",
      "Anguía",
      "Chadín",
      "Chiguirip",
      "Chimban",
      "Choropampa",
      "Cochabamba",
      "Conchán",
      "Huambos",
      "Lajas",
      "Llama",
      "Miracosta",
      "Paccha",
      "Pion",
      "Querocoto",
      "San Juan de Licupis",
      "Tacabamba",
      "Tocmoche",
    ],
    Contumazá: [
      "Contumazá",
      "Chilete",
      "Cupisnique",
      "Guzmango",
      "San Benito",
      "Santa Cruz de Toledo",
      "Tantarica",
      "Yonán",
    ],
    Cutervo: [
      "Cutervo",
      "Callayuc",
      "Choros",
      "Cujillo",
      "La Ramada",
      "Pimpingos",
      "Querocotillo",
      "San Andrés de Cutervo",
      "San Juan de Cutervo",
      "San Luis de Lucma",
      "Santa Cruz",
      "Santo Domingo de la Capilla",
      "Santo Tomás",
      "Socota",
      "Toribio Casanova",
    ],
    Hualgayoc: [
      "Bambamarca",
      "Chugur",
      "Hualgayoc",
    ],
    Jaén: [
      "Jaén",
      "Bellavista",
      "Chontali",
      "Colasay",
      "Huabal",
      "Las Pirias",
      "Pomahuaca",
      "Pucará",
      "Sallique",
      "San Felipe",
      "San José del Alto",
      "Santa Rosa",
    ],
    "San Ignacio": [
      "San Ignacio",
      "Chirinos",
      "Huarango",
      "La Coipa",
      "Namballe",
      "San José de Lourdes",
      "Tabaconas",
    ],
    "San Marcos": [
      "San Pedro de Lloc",
      "Chancay",
      "Eduardo Villanueva",
      "Gregorio Pita",
      "Ichocán",
      "José Manuel Quiroz",
      "José Sabogal",
    ],
    "San Miguel": [
      "San Miguel",
      "Bolívar",
      "Calquis",
      "Catilluc",
      "El Prado",
      "La Florida",
      "Llapa",
      "Nanchoc",
      "Niepos",
      "San Gregorio",
      "San Silvestre de Cochán",
      "Tongod",
      "Unión Agua Blanca",
    ],
    "San Pablo": [
      "San Pablo",
      "San Bernardino",
      "San Luis",
      "Tumbaden",
    ],
    SantaCruz: [
      "Santa Cruz",
      "Andabamba",
      "Catache",
      "Chancaybaños",
      "La Esperanza",
      "Ninabamba",
      "Pulán",
      "Saucepampa",
      "Sexi",
      "Uticyacu",
      "Yauyucan",
    ],
  },
  Callao: {
    Callao: [
      "Callao",
      "Bellavista",
      "Carmen de la Legua Reynoso",
      "La Perla",
      "La Punta",
      "Mi Perú",
      "Ventanilla",
    ],
  },
  Cusco: {
    Cusco: [
      "Cusco",
      "Ccorca",
      "Poroy",
      "San Jerónimo",
      "San Sebastián",
      "Santiago",
      "Saylla",
      "Wanchaq",
    ],
    Acomayo: ["Acomayo", "Acopia", "Acos", "Mosoc Llacta", "Pomacanchi", "Rondocan", "Sangarará"],
    Anta: ["Anta", "Ancahuasi", "Cachimayo", "Chinchaypujio", "Huarocondo", "Limatambo", "Mollepata", "Pucyura", "Zurite"],
    Calca: ["Calca", "Coya", "Lamay", "Lares", "Pisac", "San Salvador", "Taray", "Yanatile"],
    Canas: ["Yanaoca", "Checca", "Kunturkanki", "Langui", "Layo", "Pampamarca", "Quehue", "Tupac Amaru"],
    Canchis: ["Sicuani", "Checacupe", "Combapata", "Marangani", "Pitumarca", "San Pablo", "San Pedro", "Tinta"],
    Chumbivilcas: ["Santo Tomás", "Capacmarca", "Chamaca", "Colquemarca", "Livitaca", "Llusco", "Quiñota", "Velille"],
    Espinar: ["Espinar", "Condoroma", "Coporaque", "Ocoruro", "Pallpata", "Pichigua", "Suyckutambo", "Alto Pichigua"],
    "La Convención": [
      "Quillabamba",
      "Echarate",
      "Huayopata",
      "Inkawasi",
      "Kimbiri",
      "Maranura",
      "Ocobamba",
      "Santa Ana",
      "Santa Teresa",
      "Vilcabamba",
      "Villa Kintiarina",
      "Villa Virgen",
      "Megantoni",
    ],
    Paruro: ["Paruro", "Accha", "Ccapi", "Colcha", "Huanoquite", "Omacha", "Paccaritambo", "Pillpinto", "Yaurisque"],
    Paucartambo: ["Paucartambo", "Caicay", "Challabamba", "Colquepata", "Huancarani", "Kosñipata"],
    Quispicanchi: ["Urcos", "Andahuaylillas", "Camanti", "Ccarhuayo", "Ccatca", "Cusipata", "Huaro", "Lucre", "Marcapata", "Ocongate", "Oropesa", "Quiquijana"],
    Urubamba: ["Urubamba", "Chinchero", "Huayllabamba", "Machupicchu", "Maras", "Ollantaytambo", "Yucay"],
  },
  Huancavelica: {
    Huancavelica: [
      "Huancavelica",
      "Acobambilla",
      "Acoria",
      "Conayca",
      "Cuenca",
      "Huachocolpa",
      "Huayllahuara",
      "Izcuchaca",
      "Laria",
      "Manta",
      "Mariscal Cáceres",
      "Moya",
      "Nuevo Occoro",
      "Palca",
      "Pilchaca",
      "Vilca",
      "Yauli",
      "Ascensión",
    ],
    Acobamba: ["Acobamba", "Andabamba", "Anta", "Caja", "Marcas", "Paucará", "Pomacocha", "Rosario"],
    "Angaraes": ["Lircay", "Anchonga", "Callanmarca", "Ccochaccasa", "Chincho", "Congalla", "Huanca-Huanca", "Huayllay Grande", "Julcamarca", "San Antonio de Antaparco", "Santo Tomás de Pata", "Secclla"],
    Castrovirreyna: ["Castrovirreyna", "Arma", "Aurahua", "Capillas", "Chupamarca", "Cocas", "Huachos", "Huamatambo", "Mollepampa", "San Juan"],
    Churcampa: ["Churcampa", "Anco", "Chinchihuasi", "El Carmen", "La Merced", "Locroja", "Paucarbamba", "San Miguel de Mayocc", "San Pedro de Coris", "Pachamarca"],
    Huaytará: ["Huaytará", "Ayaví", "Córdova", "Huayacundo Arma", "Izcuchaca", "Laramarca", "Ocoyo", "Pilpichaca", "Querco", "Quito-Arma", "San Antonio de Cusicancha", "San Francisco de Sangayaico", "San Isidro", "Santiago de Chocorvos", "Santiago de Quirahuará", "Santo Domingo de Capillas", "Tambo"],
    Tayacaja: ["Pampas", "Acostambo", "Acraquia", "Ahuaycha", "Colcabamba", "Daniel Hernández", "Huachocolpa", "Huaribamba", "Ñahuimpuquio", "Pazos", "Quishuar", "Salcabamba", "Salcahuasi", "San Marcos de Rocchac", "Surcubamba", "Tintay Puncu", "Roble"],
  },
  Huánuco: {
    Huánuco: [
      "Huánuco",
      "Chinchao",
      "Churubamba",
      "Margos",
      "Quisqui",
      "San Francisco de Cayrán",
      "San Pedro de Chaulán",
      "Santa María del Valle",
      "Yarumayo",
      "Pillco Marca",
      "Conchamarca",
      "San Juan de Yacán",
    ],
    Ambo: ["Ambo", "Cayna", "Colpas", "Conchamarca", "Huacar", "San Francisco", "San Rafael", "Tomay Kichwa"],
    "Dos de Mayo": ["La Unión", "Chuquis", "Marías", "Pachas", "Quivilla", "Ripan", "Shunqui", "Sillapata", "Yanas"],
    Huacaybamba: ["Huacaybamba", "Canchabamba", "Cochabamba", "Pinra"],
    Huamalíes: ["Llata", "Arancay", "Chavín de Pariarca", "Jacas Grande", "Jircan", "Miraflores", "Monzón", "Punchao", "Puños", "Singa", "Tantamayo"],
    LeoncioPrado: ["Rupa-Rupa", "Daniel Alomía Robles", "Hermílio Valdizán", "José Crespo y Castillo", "Luyando", "Mariano Dámaso Beraún", "Pucayacu", "Castillo Grande", "Pueblo Nuevo"],
    Marañón: ["Huacrachuco", "Cholon", "San Buenaventura"],
    Pachitea: ["Panao", "Chaglla", "Molino", "Umari"],
    PuertoInca: ["Puerto Inca", "Codo del Pozuzo", "Honoria", "Tournavista", "Yuyapichis"],
    Lauricocha: ["Jesús", "Baños", "Jivia", "Queropalca", "Rondos", "San Francisco de Asís", "San Miguel de Cauri"],
    Yarowilca: ["Chavínillo", "Cahuac", "Chacabamba", "Aparicio Pomares", "Jacas Chico", "Obas", "Pampamarca", "Santa María"],
  },
  Ica: {
    Ica: [
      "Ica",
      "La Tinguiña",
      "Los Aquijes",
      "Ocucaje",
      "Pachacútec",
      "Parcona",
      "Pueblo Nuevo",
      "Salas",
      "San José de los Molinos",
      "San Juan Bautista",
      "Santiago",
      "Subtanjalla",
      "Tate",
      "Yauca del Rosario",
    ],
    Chincha: [
      "Chincha Alta",
      "Alto Larán",
      "Chavin",
      "Chincha Baja",
      "El Carmen",
      "Grocio Prado",
      "Pueblo Nuevo",
      "San Juan de Yanac",
      "San Pedro de Huacarpana",
      "Sunampe",
      "Tambo de Mora",
    ],
    "Nazca": ["Nazca", "Changuillo", "El Ingenio", "Marcona", "Vista Alegre"],
    Palpa: ["Palpa", "Llipata", "Río Grande", "Santa Cruz", "Tibillo"],
    Pisco: ["Pisco", "Huancano", "Humay", "Independencia", "Paracas", "San Andrés", "San Clemente", "Túpac Amaru Inca"],
  },
  Junín: {
    Huancayo: [
      "Huancayo",
      "Carhuacallanga",
      "Chacapampa",
      "Chicche",
      "Chilca",
      "Chongos Alto",
      "Chupuro",
      "Colca",
      "Cullhuas",
      "El Tambo",
      "Huacrapuquio",
      "Hualhuas",
      "Huancán",
      "Huayucachi",
      "Ingenio",
      "Pariahuanca",
      "Pilcomayo",
      "Pucará",
      "Quichuay",
      "Quilcas",
      "San Agustín de Cajas",
      "San Jerónimo de Tunán",
      "San Pedro de Saño",
      "Santo Domingo de Acobamba",
      "Saño",
      "Sapallanga",
      "Sicaya",
      "Tres de Diciembre",
      "Viques",
    ],
    Concepción: ["Concepción", "Andamarca", "Ahuac", "Cochas", "Comas", "Mariscal Castilla", "Matahuasi", "Mito", "Nueve de Julio", "Orcotuna", "San José de Quero", "Santa Rosa de Ocopa"],
    Chanchamayo: ["Chanchamayo", "Perené", "Pichanaqui", "San Luis de Shuaro", "San Ramón", "Vitoc"],
    Jauja: ["Jauja", "Acolla", "Apata", "Ataura", "Canchayllo", "Curicaca", "El Mantaro", "Huamalí", "Huaripampa", "Huertas", "Janjaillo", "Julcán", "Leonor Ordóñez", "Llocllapampa", "Marco", "Masma", "Masma Chicche", "Molinos", "Monobamba", "Muqui", "Muquiyauyo", "Paca", "Paccha", "Pancán", "Parco", "Pomacancha", "Ricrán", "San Lorenzo", "San Pedro de Chunán", "Sausa", "Sincos", "Tunan Marca", "Yauli", "Yauyos"],
    Junín: ["Junín", "Carhuamayo", "Ondores", "Ulcumayo"],
    Satipo: ["Satipo", "Coviriali", "Llaylla", "Mazamari", "Pangoa", "Pichari", "Rio Negro", "Rio Tambo"],
    Tarma: ["Tarma", "Acobamba", "Huaricolca", "Huasahuasi", "La Unión", "Palca", "Palcamayo", "San Pedro de Cajas", "Tapo"],
    Yauli: ["La Oroya", "Chacapalpa", "Huay-Huay", "Marcapomacocha", "Morococha", "Paccha", "Santa Bárbara de Carhuacayán", "Santa Rosa de Sacco", "Suitucancha", "Yauli"],
    Chupaca: ["Chupaca", "Ahuac", "Chongos Bajo", "Huachac", "Huamancaca Chico", "San Juan de Yscos", "San Juan de Jarpa", "Tres de Diciembre", "Yanacancha"],
  },
  "La Libertad": {
    Trujillo: [
      "Trujillo",
      "El Porvenir",
      "Florencia de Mora",
      "Huanchaco",
      "La Esperanza",
      "Laredo",
      "Moche",
      "Poroto",
      "Salaverry",
      "Simbal",
      "Victor Larco Herrera",
    ],
    Ascope: ["Ascope", "Chicama", "Chocope", "Magdalena de Cao", "Paiján", "Rázuri", "Santiago de Cao"],
    Bolívar: ["Bolívar", "Bambamarca", "Condormarca", "Longotea", "Uchumarca", "Ucuncha"],
    Chepén: ["Chepén", "Pacanga", "Pueblo Nuevo"],
    Julcán: ["Julcán", "Calamarca", "Carabamba", "Huaso"],
    Otuzco: ["Otuzco", "Agallpampa", "Charat", "Huaranchal", "La Cuesta", "Mache", "Paranday", "Salpo", "Sinsicap"],
    Pacasmayo: ["San Pedro de Lloc", "Guadalupe", "Jequetepeque", "Pacasmayo", "San José"],
    Pataz: ["Tayabamba", "Buldibuyo", "Chillia", "Huancaspata", "Huaylillas", "Huayo", "Ongón", "Parcoy", "Pataz", "Pias", "Santiago de Challas", "Taurija", "Urpay"],
    SánchezCarrión: ["Huamachuco", "Chugay", "Cochorco", "Curgos", "Marcabal", "Sanagorán", "Sarín", "Sartimbamba"],
    SantiagoDeChuco: ["Santiago de Chuco", "Angasmarca", "Cachicadán", "Mollebamba", "Mollepata", "Quiruvilca", "Santa Cruz de Chuca", "Sitabamba"],
    GranChimú: ["Cascas", "Lucma", "Marmot", "Sayapullo"],
    Virú: ["Virú", "Chao", "Guadalupito"],
  },
  Lambayeque: {
    Chiclayo: [
      "Chiclayo",
      "Chongoyape",
      "Eten",
      "Eten Puerto",
      "José Leonardo Ortiz",
      "La Victoria",
      "Lagunas",
      "Monsefú",
      "Nueva Arica",
      "Oyotún",
      "Picsi",
      "Pimentel",
      "Reque",
      "Santa Rosa",
      "Saña",
      "Cayaltí",
      "Pátapo",
      "Mochumí",
      "Tumán",
    ],
    Ferreñafe: ["Ferreñafe", "Cañaris", "Incahuasi", "Manuel Antonio Mesones Muro", "Pitipo", "Pueblo Nuevo"],
    Lambayeque: ["Lambayeque", "Chóchope", "Illimo", "Jayanca", "Mochumí", "Mórrope", "Motupe", "Olmos", "Pacora", "Salas", "San José", "Túcume"],
  },
  Lima: {
    Lima: [
      "Lima",
      "Ancón",
      "Ate",
      "Barranco",
      "Breña",
      "Carabayllo",
      "Chaclacayo",
      "Chorrillos",
      "Cieneguilla",
      "Comas",
      "El Agustino",
      "Independencia",
      "Jesús María",
      "La Molina",
      "La Victoria",
      "Lince",
      "Los Olivos",
      "Lurigancho-Chosica",
      "Lurín",
      "Magdalena del Mar",
      "Miraflores",
      "Pachacámac",
      "Pucusana",
      "Pueblo Libre",
      "Puente Piedra",
      "Punta Hermosa",
      "Punta Negra",
      "Rímac",
      "San Bartolo",
      "San Borja",
      "San Isidro",
      "San Juan de Lurigancho",
      "San Juan de Miraflores",
      "San Luis",
      "San Martín de Porres",
      "San Miguel",
      "Santa Anita",
      "Santa María del Mar",
      "Santa Rosa",
      "Santiago de Surco",
      "Surquillo",
      "Villa El Salvador",
      "Villa María del Triunfo",
    ],
    Barranca: ["Barranca", "Paramonga", "Pativilca", "Supe", "Supe Puerto"],
    Cajatambo: ["Cajatambo", "Copa", "Gorgor", "Huancapón", "Manas"],
    Canta: ["Canta", "Arahuay", "Huamantanga", "Huaros", "Lachaqui", "San Buena Ventura", "Santa Rosa de Quives"],
    "Cañete": [
      "San Vicente de Cañete",
      "Asia",
      "Calango",
      "Cerro Azul",
      "Chilca",
      "Coayllo",
      "Imperial",
      "Lunahuaná",
      "Mala",
      "Nuevo Imperial",
      "Pacarán",
      "Quilmaná",
      "San Antonio",
      "San Luis",
      "Santa Cruz de Flores",
      "Zúñiga",
    ],
    Huaral: ["Huaral", "Atavillos Alto", "Atavillos Bajo", "Aucallama", "Chancay", "Ihuari", "Lampián", "Pacaraos", "San Miguel de Acos", "Santa Cruz de Andamarca", "Sumbilca", "Veintisiete de Noviembre"],
    Huarochirí: ["Matucana", "Antioquía", "Callahuanca", "Carampoma", "Caucaya", "Cochacharao", "Copaquilla", "Cuenca", "Huachupampa", "Huanza", "Huarochirí", "Lahuaytambo", "Langa", "Laraos", "Mariatana", "Ricardo Palma", "San Andrés de Tupicocha", "San Antonio de Chaclla", "San Bartolomé", "San Damián", "San Juan de Iris", "San Juan de Tantaranche", "San Lorenzo de Quinti", "San Mateo", "San Mateo de Otao", "San Pedro de Casta", "San Pedro de Huancayre", "Sangallaya", "Santa Cruz de Cocachacra", "Santa Eulalia", "Santiago de Anchucaya", "Santiago de Tuna", "Santo Domingo de los Olleros", "Surco", "Tupicocha"],
    Huaura: ["Huacho", "Ambar", "Caleta de Carquín", "Checras", "Hualmay", "Huaura", "Leoncio Prado", "Paccho", "Santa Leonor", "Santa María", "Sayan", "Vegueta"],
    Oyón: ["Oyón", "Andajes", "Caujul", "Cochamarca", "Naván", "Pachangara"],
    Yauyos: ["Yauyos", "Alis", "Allauca", "Ayaviri", "Azángaro", "Cacra", "Carania", "Catahuasi", "Chocos", "Cochas", "Colonia", "Hongos", "Huampara", "Huancaya", "Huangáscar", "Huantán", "Huañec", "Laraos", "Lincha", "Madean", "Miraflores", "Omas", "Putinza", "Quinches", "Quinocay", "San Joaquín", "San Pedro de Pilas", "Tanta", "Tauripampa", "Tomas", "Tupe", "Viñac", "Vitis"],
  },
  Loreto: {
    Maynas: [
      "Iquitos",
      "Alto Nanay",
      "Fernando Lores",
      "Indiana",
      "Las Amazonas",
      "Mazán",
      "Napo",
      "Punchana",
      "Putumayo",
      "Torres Causana",
      "Teniente Manuel Clavero",
    ],
    "Alto Amazonas": ["Yurimaguas", "Balsapuerto", "Jeberos", "Lagunas", "Santa Cruz", "Teniente César López Rojas"],
    "Loreto": ["Nauta", "Cabo Pantoja", "Campanquiz", "Marañón", "Morona", "Pastaza", "Tigre", "Trompeteros", "Urarinas"],
    "Mariscal Ramón Castilla": ["Ramón Castilla", "Pebas", "San Pablo", "Yavari"],
    "Requena": ["Requena", "Alto Tapiche", "Capelo", "Emilio San Martín", "Jenaro Herrera", "Mazán", "Puinahua", "Saquena", "Soplín", "Tapiche"],
    "Ucayali": ["Contamana", "Inahuaya", "Padre Márquez", "Pampa Hermosa", "Sarayacu", "Vargas Guerra"],
    "Datem del Marañón": ["Barranca", "Andoas", "Cahuapanas", "Manseriche", "Morona", "Pastaza"],
    Putumayo: ["Putumayo", "Rosa Panduro", "Teniente Manuel Clavero", "Yaguas"],
  },
  "Madre de Dios": {
    Tambopata: ["Tambopata", "Inambari", "Las Piedras", "Laberinto"],
    Manu: ["Manu", "Fitzcarrald", "Madre de Dios", "Huepetuhe"],
    Tahuamanu: ["Iñapari", "Iberia", "Tahuamanu"],
  },
  Moquegua: {
    "Mariscal Nieto": [
      "Moquegua",
      "Carumas",
      "Cuchumbaya",
      "Samegua",
      "San Cristóbal de Calacoa",
      "Torata",
    ],
    "General Sánchez Cerro": ["Omate", "Chojata", "Coalaque", "Ichuña", "La Capilla", "Lloque", "Matalaque", "Puquina", "Quinistaquillas", "San Juan de Tarucani", "Ubinas", "Yunga"],
    Ilo: ["Ilo", "El Algarrobal", "Pacocha"],
  },
  Pasco: {
    Pasco: ["Chaupimarca", "Huachón", "Huariaca", "Huayllay", "Ninacaca", "Pallanchacra", "Paucartambo", "San Francisco de Asís de Yarusyacán", "Simón Bolívar", "Ticlacayán", "Tinyahuarco", "Vicco", "Yanacancha"],
    "Daniel Alcides Carrión": ["Yanahuanca", "Chacayán", "Goyllarisquizga", "Paucar", "San Pedro de Pillao", "Santa Ana de Tusi", "Tapuc", "Vilcabamba"],
    Oxapampa: ["Oxapampa", "Chontabamba", "Huancabamba", "Palcazú", "Pozuzo", "Puerto Bermúdez", "Villa Rica", "Constitución"],
  },
  Piura: {
    Piura: ["Piura", "Castilla", "Catacaos", "Cura Mori", "El Tallán", "La Arena", "La Unión", "Las Lomas", "Tambo Grande", "Veintiséis de Octubre"],
    Ayabaca: ["Ayabaca", "Frías", "Jililí", "Lagunas", "Montero", "Pacaipampa", "Paimas", "Sapillica", "Sícchez", "Suyo"],
    Huancabamba: ["Huancabamba", "Canchaque", "El Carmen de la Frontera", "Huarmaca", "Lalaquiz", "San Miguel de El Faique", "Sóndor", "Sondorillo"],
    Morropón: ["Chulucanas", "Buenos Aires", "Chalaco", "La Matanza", "Morropón", "Salitral", "San Juan de Bigote", "Santa Catalina de Mossa", "Santo Domingo", "Yamango"],
    Paita: ["Paita", "Amotape", "Colán", "El Arenal", "La Huaca", "Tamarindo", "Vichayal"],
    Sullana: ["Sullana", "Bellavista", "Ignacio Escudero", "Lancones", "Marcavelica", "Miguel Checa", "Querecotillo", "Salitral"],
    Talara: ["Pariñas", "El Alto", "La Brea", "Lobitos", "Los Órganos", "Máncora", "Arenal"],
    Sechura: ["Sechura", "Bellavista de la Unión", "Bernal", "Cristo Nos Valga", "Vice", "Rinconada Llicuar"],
  },
  Puno: {
    Puno: ["Puno", "Acora", "Amantani", "Atuncolla", "Capachica", "Chucuito", "Coata", "Huata", "Mañazo", "Nicasio", "Paucarcolla", "Pichacani", "Platería", "San Antonio", "Tiquillaca", "Vilque"],
    Azángaro: ["Azángaro", "Achaya", "Arapa", "Asillo", "Caminaca", "Chupa", "José Domingo Choquehuanca", "Muñani", "Potoni", "Saman", "San Antón", "San José", "San Juan de Salinas", "Santiago de Pupuja", "Tirapata"],
    Carabaya: ["Macusani", "Ajoyani", "Ayapata", "Coasa", "Corani", "Crucero", "Ituata", "Ollachea", "San Gaban", "Usicayos"],
    Chucuito: ["Juli", "Desaguadero", "Huacullani", "Kelluyo", "Pisacoma", "Pomata", "Zepita"],
    "El Collao": ["Ilave", "Capazo", "Conduriri", "Pilcuyo", "Santa Rosa"],
    Huancané: ["Huancané", "Cojata", "Huatasani", "Inchupalla", "Pusi", "Rosaspata", "Taraco", "Vilque Chico"],
    Lampa: ["Lampa", "Cabanilla", "Calapuja", "Nicasio", "Ocuviri", "Palca", "Paratia", "Pucará", "Santa Lucía", "Vilavila"],
    Melgar: ["Ayaviri", "Antauta", "Cupi", "Llalli", "Macari", "Nuñoa", "Orurillo", "Santa Rosa", "Umachiri"],
    Moho: ["Moho", "Conima", "Huayrapata", "Tilali"],
    "San Antonio de Putina": ["Putina", "Ananea", "Pedro Vilcapaza", "Quilcapuncu", "San Juan del Oro", "Yanahuaya"],
    "San Román": ["Juliaca", "Cabana", "Cabanillas", "Caracoto"],
    Sandia: ["Sandia", "Cuyocuyo", "Limbani", "Patambuco", "Phara", "Quiaca", "San Juan del Oro", "Yanahuaya", "Alto Inambari", "San Pedro de Putina Punco"],
    Yunguyo: ["Yunguyo", "Anapia", "Copani", "Cuturapi", "Ollaraya", "Tinicachi", "Unicachi"],
  },
  "San Martín": {
    Moyobamba: ["Moyobamba", "Calzada", "Habana", "Jepelacio", "Soritor", "Yantalo"],
    Bellavista: ["Bellavista", "Alto Biavo", "Bajo Biavo", "Huallaga", "San Pablo", "San Rafael"],
    "El Dorado": ["San José de Sisa", "Agua Blanca", "San Martín", "Santa Rosa", "Shatoja"],
    Huallaga: ["Saposoa", "Alto Saposoa", "El Eslabón", "Huallaga", "Piscoyacu", "Sacanche", "Tingo de Saposoa", "Tres Unidos"],
    Lamas: ["Lamas", "Alonso de Alvarado", "Barranquita", "Caynarachi", "Cuñumbuqui", "Pinto Recodo", "Rumisapa", "San Roque de Cumbaza", "Shanao", "Tabalosos", "Zapatero"],
    MariscalCáceres: ["Juanjuí", "Campanilla", "Huicungo", "La Bicoca", "Pachiza", "Pajarillo"],
    Picota: ["Picota", "Buenos Aires", "Caspisapa", "Pilluana", "Pucacaca", "San Cristóbal", "San Hilarión", "Shamboyacu", "Tingo de Ponasa", "Tres Unidos"],
    Rioja: ["Rioja", "Awajun", "Cajamarca", "Elías Soplín Vargas", "Nueva Cajamarca", "Pardo Miguel", "Posic", "San Fernando", "Yorongos", "Yuracyacu"],
    SanMartín: ["Tarapoto", "Alberto Leveau", "Cacatachi", "Chazuta", "Chipurana", "El Porvenir", "Huimbayoc", "Juan Guerra", "La Banda de Shilcayo", "Morales", "Papaplaya", "San Antonio", "Sauce", "Shapaja"],
    Tocache: ["Tocache", "Nuevo Progreso", "Pólvora", "Shunte", "Uchiza"],
  },
  Tacna: {
    Tacna: ["Tacna", "Alto de la Alianza", "Calana", "Ciudad Nueva", "Inclán", "Pachía", "Palca", "Pocollay", "Sama", "Coronel Gregorio Albarracín Lanchipa", "La Yarada-Los Palos"],
    Candarave: ["Candarave", "Cairani", "Camilaca", "Curibaya", "Huanuara", "Quilahuani"],
    JorgeBasadre: ["Locumba", "Ilabaya", "Ite"],
    Tarata: ["Tarata", "Héroes Albarracín", "Estique", "Estique-Pampa", "Sitajara", "Susapaya", "Tarucachi", "Ticaco"],
  },
  Tumbes: {
    Tumbes: ["Tumbes", "Corrales", "La Cruz", "Pampas de Hospital", "San Jacinto", "San Juan de la Virgen"],
    "Contralmirante Villar": ["Zorritos", "Casitas", "Canoas de Punta Sal"],
    Zarumilla: ["Zarumilla", "Aguas Verdes", "Matapalo", "Papayal"],
  },
  Ucayali: {
    "Coronel Portillo": [
      "Callería",
      "Campo Verde",
      "Iparía",
      "Masisea",
      "Yarinacocha",
      "Nueva Requena",
      "Manantay",
      "Yarinacocha",
    ],
    Atalaya: ["Raymondi", "Sepahua", "Tahuanía", "Yurúa"],
    PadreAbad: ["Padre Abad", "Irazola", "Curimaná", "Neshuya", "Alexander Von Humboldt"],
    Purús: ["Purús"],
  },
};

export function getDepartamentos(): string[] {
  return Object.keys(PERU_UBIGEO);
}

export function getProvincias(departamento: string): string[] {
  return Object.keys(PERU_UBIGEO[departamento] ?? {});
}

export function getDistritos(departamento: string, provincia: string): string[] {
  return PERU_UBIGEO[departamento]?.[provincia] ?? [];
}